name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIASWCJ2ADC7EJ2WULW }}
          aws-secret-access-key: ${{ secrets.TSGBpuHM7JMeaWya9C8ffCaz+8hF8phLgHYGLDLa }}
          aws-region: us-east-1

      # Login to Docker Hub
      - name: Docker Hub Login
        run: echo "${{ secrets.Petert_2024 }}" | docker login -u "${{ secrets.taiwopeterolatunji }}" --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t devops-app ./app

      # Tag Docker image
      - name: Tag Docker Image
        run: docker tag devops-app ${{ secrets.taiwopeterolatunji }}/devops-app:latest

      # Push Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.taiwopeterolatunji }}/devops-app:latest

      # Deploy to ECS
      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster devops-cluster \
            --service devops-service \
            --force-new-deployment